package dc

import org.apache.spark.sql.{SparkSession, DataFrame}

object UPUtil {

  /**
   * root
   * |-- start_date: string (nullable = true)
   * |-- change_code: string (nullable = true)
   * |-- key: string (nullable = true)
   * |-- open_udid: string (nullable = true)
   * |-- update_time: string (nullable = true)
   * |-- basic_device_os: string (nullable = true)
   * |-- basic_device_ver: string (nullable = true)
   * |-- basic_device_net: string (nullable = true)
   * |-- basic_device_isp: string (nullable = true)
   * |-- basic_device_phone: string (nullable = true)
   * |-- basic_device_schannel: string (nullable = true)
   * |-- basic_device_push_status: string (nullable = true)
   * |-- basic_device_intall_time: string (nullable = true)
   * |-- basic_device_cpt_intall: string (nullable = true)
   * |-- basic_account_id: string (nullable = true)
   * |-- basic_account_name: string (nullable = true)
   * |-- basic_account_level: string (nullable = true)
   * |-- basic_account_reg_time: string (nullable = true)
   * |-- basic_account_sex: string (nullable = true)
   * |-- basic_account_age: string (nullable = true)
   * |-- basic_nature_sex_sales: string (nullable = true)
   * |-- basic_nature_age_sales: string (nullable = true)
   * |-- basic_loc_last: string (nullable = true)
   * |-- basic_loc_general: string (nullable = true)
   * |-- basic_loc_general_asyn: string (nullable = true)
   * |-- basic_loc_history: string (nullable = true)
   * |-- basic_loc_country: string (nullable = true)
   * |-- basic_loc_province: string (nullable = true)
   * |-- basic_loc_city: string (nullable = true)
   * |-- basic_loc_firstforeign_dt: string (nullable = true)
   * |-- basic_loc_lastforeign_dt: string (nullable = true)
   * |-- action_client_lastin: string (nullable = true)
   * |-- action_read_page_num: string (nullable = true)
   * |-- action_read_expose_num: string (nullable = true)
   * |-- action_search_history_search: string (nullable = true)
   * |-- action_search_num: string (nullable = true)
   * |-- basic_account_friend_num: string (nullable = true)
   * |-- basic_account_fans_num: string (nullable = true)
   * |-- basic_account_pmsg_num: string (nullable = true)
   * |-- basic_loc_general_level: string (nullable = true)
   * |-- basic_loc_top_five: string (nullable = true)
   * |-- action_client_open_num: string (nullable = true)
   * |-- recent_action_client_open_num: string (nullable = true)
   * |-- action_client_sign_30d: string (nullable = true)
   * |-- action_client_lanuch_30d: string (nullable = true)
   * |-- action_read_page_num_travel: string (nullable = true)
   * |-- action_read_page_num_guide: string (nullable = true)
   * |-- action_read_page_num_qa: string (nullable = true)
   * |-- action_read_page_num_weng: string (nullable = true)
   * |-- recent_action_read_page_num_travel: string (nullable = true)
   * |-- recent_action_read_page_num_guide: string (nullable = true)
   * |-- recent_action_read_page_num_qa: string (nullable = true)
   * |-- recent_action_read_page_num_weng: string (nullable = true)
   * |-- recent_action_search_num: string (nullable = true)
   * |-- action_store_num: string (nullable = true)
   * |-- recent_action_store_num: string (nullable = true)
   * |-- action_ugc_note_num: string (nullable = true)
   * |-- action_ugc_note_top_num: string (nullable = true)
   * |-- action_ugc_note_focus_num: string (nullable = true)
   * |-- action_ugc_question_num: string (nullable = true)
   * |-- action_ugc_answer_num: string (nullable = true)
   * |-- action_ugc_answer_gold_num: string (nullable = true)
   * |-- action_ugc_weng_num: string (nullable = true)
   * |-- action_ugc_commons_num: string (nullable = true)
   * |-- action_ugc_rate_travel: string (nullable = true)
   * |-- action_ugc_rate_qa: string (nullable = true)
   * |-- action_ugc_rate_weng: string (nullable = true)
   * |-- action_sales_page_num: string (nullable = true)
   * |-- action_sales_expose_num: string (nullable = true)
   * |-- action_sales_order_num: string (nullable = true)
   * |-- action_sales_gmv: string (nullable = true)
   * |-- action_sales_avg_gmv: string (nullable = true)
   * |-- action_sales_order_num_365d: string (nullable = true)
   * |-- action_sales_gmv_365d: string (nullable = true)
   * |-- value_action_general_level: string (nullable = true)
   * |-- value_sales_general_level: string (nullable = true)
   * |-- value_ugc_general_level: string (nullable = true)
   * |-- basic_device_phone_brand: string (nullable = true)
   * |-- action_client_duration: string (nullable = true)
   * |-- recent_action_client_duration: string (nullable = true)
   * |-- action_travel_num: string (nullable = true)
   * |-- action_travel_num365d: string (nullable = true)
   * |-- action_sales_storenum: string (nullable = true)
   * |-- action_sales_orderwill: string (nullable = true)
   * |-- action_ugc_commonsactnum: string (nullable = true)
   * |-- action_ugc_qaexpert: string (nullable = true)
   * |-- basic_nature_age: string (nullable = true)
   * |-- basic_nature_sex: string (nullable = true)
   * |-- basic_travel_status: string (nullable = true)
   * |-- value_action_generalscore: string (nullable = true)
   * |-- value_action_role: string (nullable = true)
   * |-- value_sales_orderlevel: string (nullable = true)
   * |-- value_sales_expectlevel: string (nullable = true)
   * |-- value_sales_generalscore: string (nullable = true)
   * |-- value_sales_orderscore: string (nullable = true)
   * |-- value_sales_expectscore: string (nullable = true)
   * |-- value_sales_role: string (nullable = true)
   * |-- value_ugc_generalscore: string (nullable = true)
   * |-- value_ugc_role: string (nullable = true)
   * |-- like_read_chmdd: string (nullable = true)
   * |-- like_read_mddid: string (nullable = true)
   * |-- like_read_poiid: string (nullable = true)
   * |-- like_read_human: string (nullable = true)
   * |-- like_read_otag: string (nullable = true)
   * |-- like_read_mtag: string (nullable = true)
   * |-- like_read_readable: string (nullable = true)
   * |-- like_read_scene: string (nullable = true)
   * |-- like_read_topic: string (nullable = true)
   * |-- like_read_transport: string (nullable = true)
   * |-- like_read_utag: string (nullable = true)
   * |-- like_read_ways: string (nullable = true)
   * |-- like_read_whilego: string (nullable = true)
   * |-- like_read_activity: string (nullable = true)
   * |-- like_read_style: string (nullable = true)
   * |-- like_read_prepare: string (nullable = true)
   * |-- like_sales_salestype: string (nullable = true)
   * |-- recent_like_read_chmdd: string (nullable = true)
   * |-- recent_like_read_mddid: string (nullable = true)
   * |-- recent_like_read_poiid: string (nullable = true)
   * |-- recent_like_read_mtag: string (nullable = true)
   * |-- recent_like_read_human: string (nullable = true)
   * |-- recent_like_read_otag: string (nullable = true)
   * |-- recent_like_read_readable: string (nullable = true)
   * |-- recent_like_read_scene: string (nullable = true)
   * |-- recent_like_read_topic: string (nullable = true)
   * |-- recent_like_read_utag: string (nullable = true)
   * |-- recent_like_read_ways: string (nullable = true)
   * |-- recent_like_read_whilego: string (nullable = true)
   * |-- recent_like_read_activity: string (nullable = true)
   * |-- recent_like_read_style: string (nullable = true)
   * |-- recent_like_read_prepare: string (nullable = true)
   * |-- recent_like_sales_salestype: string (nullable = true)
   * |-- basic_account_typevip: string (nullable = true)
   * |-- basic_nature_zodiac: string (nullable = true)
   * |-- basic_type_fresh: string (nullable = true)
   * |-- basic_type_prefer: string (nullable = true)
   * |-- action_client_hudonglist: string (nullable = true)
   * |-- action_ugc_totalnum: string (nullable = true)
   * |-- action_ugc_wengselectnum: string (nullable = true)
   * |-- action_ugc_guidenum: string (nullable = true)
   * |-- action_ugc_guideselectnum: string (nullable = true)
   * |-- action_sales_orderlist: string (nullable = true)
   * |-- like_report_otaglist: string (nullable = true)
   * |-- like_report_otagtime: string (nullable = true)
   * |-- basic_loc_intent: string (nullable = true)
   * |-- basic_loc_intenttop: string (nullable = true)
   * |-- action_ugc_history: string (nullable = true)
   * |-- action_client_foot_light4mdd: string (nullable = true)
   * |-- action_ugc_videonum: string (nullable = true)
   * |-- like_read_qxbtag: string (nullable = true)
   * |-- recent_like_read_qxbtag: string (nullable = true)
   * |-- basic_type_hpdepth_lv1: string (nullable = true)
   * |-- basic_type_hpdepth_lv2: string (nullable = true)
   * |-- basic_type_hpdepth_lv1_7d: string (nullable = true)
   * |-- basic_type_hpdepth_lv2_7d: string (nullable = true)
   * |-- basic_type_depth: string (nullable = true)
   * |-- basic_type_shequ: string (nullable = true)
   * |-- basic_type_uav: string (nullable = true)
   * |-- like_read_t1: string (nullable = true)
   * |-- like_read_t2: string (nullable = true)
   * |-- like_read_t3: string (nullable = true)
   * |-- like_read_t4: string (nullable = true)
   * |-- recent_like_read_t1: string (nullable = true)
   * |-- recent_like_read_t2: string (nullable = true)
   * |-- recent_like_read_t3: string (nullable = true)
   * |-- recent_like_read_t4: string (nullable = true)
   * |-- dp: string (nullable = true)
   * |-- dt: string (nullable = true)
   * |-- end_date: string (nullable = true)
   */
  def getUserProfile(dt: String, spark: SparkSession): DataFrame = {
    val sql =
      """
        |select
        | *
        |from
        | mfw_ods.origin_upf_dep__usercenter_official_his
        |where
        | start_date<='%s' and end_date>'%s'
      """.stripMargin.format(dt, dt)

    spark.sql(sql)
  }

}
